version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: blog-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: blogpass
      POSTGRES_DB: blogdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
